### PR TITLE
Fix long lines

### LINKED ISSUE #4: Truncated logs
Hi,

sometimes the first few bytes of a log message are missing

```
O[30926] Registering on the discovery service every 20s...  
```

which should be 

```
INFO[30926] Registering on the discovery service every 20s...  
```

Do you have any idea, how this could happen? 
When I use 'docker logs', I can see that 'INFO' is colored (ANSI Escape Sequence)

### PR DESCRIPTION
**Pull request by cammellos**
This handle the case when the chunk includes multiple headers or no headers. 
Fixes #4

### CODE REVIEW

File: lib/parser.js [hunk 1]
```diff
@@ -28,30 +28,38 @@ function parser (data, opts) {
...
+        buffer = buffer.shallowSlice(readHeaders.length)
 
         if (this.headers.length !== 8) {
           return cb()
         }
 
         this.readingHeader = false
         this.payloadLength = this.headers.readUInt32BE(4)
-        this.headers.consume(8)
+        this.headers = bl()
```
Comment (mcollina) [inline lib/parser.js]: I think we should keep the same instance of `bl` around. Why are you resetting it?

Comment (cammellos) [reply lib/parser.js]: I thought it would look a bit more explicit, but don't mind changing it back, I will change back line 71 as well, thanks

**Comment by megastef** [comment]
Looks good.
